"""added password field

Revision ID: 930cd137e34e
Revises: 
Create Date: 2022-04-29 00:54:11.290030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930cd137e34e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
